version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
    hostname: ${INSTANCE_NAME_APP}
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start
    environment:
      - PORT=3000
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - INSTANCE_NAME_APP=${INSTANCE_NAME_APP}
      - INSTANCE_NAME_DB=${INSTANCE_NAME_DB}
      - MONGO_URL=mongodb://mongo-db:28000/cartographer
    ports:
      - 3000:3000
    depends_on:
      - neo4j-db
      - mongo-db

  neo4j-db:
    image: neo4j
    hostname: ${INSTANCE_NAME_DB}
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  mongo-db:
    image: mongo
    hostname: mongo-db
    command: mongod --port 28000 # Change internal port to 28000
    volumes:
      - mongo-data:/data/db
    ports:
      - 28000:28000 # Map custom external port to the new internal port

volumes:
  neo4j-data:
  mongo-data:
