const tokenMap = {
  "Airtable": "airtable",
  "AliExpress": "aliexpress",
  "BambooHR": "bamboohr",
  "Brex Dashboard": "brex",
  "Checkr Dashboard": "checkr",
  "Clerky": "clerky",
  "Deel": "deel",
  "Docker": "docker",
  "Excalidraw+": "excalidraw",
  "Fantastical": "fantastical",
  "Fantastical for iOS": "fantastical",
  "Fiverr": "fiverr",
  "GlassDoor": "glassdoor",
  "Google Chrome": "google-chrome",
  "GRID": "getgridapp",
  "Guild.xyz": "guildxyz",
  "Gusto": "gusto",
  "iOS": "ios",
  "iOS Account Manager": "ios",
  "Looker Studio": "lookerstudio",
  "Loom": "loom",
  "Microsoft Google Play Android Developer Account": "microsoft-google-play-android-developer-account",
  "Miro": "miro",
  "Navigraph": "navigraph",
  "Next Insurance": "nextinsurance",
  "Notion": "notion",
  "Notion2Charts": "notion2charts",
  "OpenAI": "openai",
  "Rows": "rows",
  "Slack": "slack",
  "Slidebean": "slidebean",
  "Super": "superso",
  "tl;dv": "tldv",
  "Webflow": "webflow",
  "Wix": "wix",
  "WordPress": "wordpress",
  "ClickUp": "clickup",
  "15Five": "15five",
  "Shutterstock": "shutterstock",
  "The QR Code Generator": "the-qr-code-generator",
  "Figma": "figma",
  "Iconscout": "iconscout",
  "Mobbin": "mobbin",
  "Leonardo Ai": "leonardoai",
  "Freepik Company": "freepik",
  "Envato": "envato",
  "Freshdesk": "freshdesk",
  "Android device": "android",
  "pdfFiller": "pdffiller",
  "Text Blaze": "textblaze",
  "User_list": "user-list",
  "Freshworks": "freshworks",
  "Calendly": "calendly",
}

module.exports = tokenMap